# Generated by Django 2.1.5 on 2019-01-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melp_res', '0002_auto_20190125_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
